- README.md
- erlang.mk
- plugins/erlydtl.mk
if DTL_FULL_PATH=true
/templates/a/b/c.dtl -> a_b_c_dtl.beam
otherwise (as it was before)
-> c_dtl.beam
With this change it will be possible to create templates with the same name in different directories.
> Make it possible to create erlydtl beam files with full path in the name

- Makefile
- test/Makefile
Makefile-based tests for a few of the erlang.mk targets. Consider this a proof of concept. It should probably be split up into one makefile per plugin or something like that.
There are several verbosity levels (V=0, 1, 2, 3) for various output. Not sure if all of these are useful.
This is the output of `make tests`:
```
make -C tests
Setting up app.
app: Testing the 'app' target.
Checking the modules line in the generated .app file.
Checking that 'make clean-app' deletes ebin.
Checking that 'make app' returns non-zero on compile errors.
Test 'app' passed.
ct: Testing tests-ct and related targets.
Setting up test suite.
Checking files created by 'make tests-ct'.
Checking that 'make clean-ct' does not delete logs.
Testing target 'ct-mysuite' where mysuite_SUITE is a test suite.
Checking …
```
> Tests for erlang.mk targets

- core/erlc.mk
- erlang.mk
- plugins/relx.mk
This pull requests adds the power of [order-only prerequisites](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html) feature of GNU make to erlang.mk.
The code is built really after its dependencies.
This fixes the need of multiple make runs with ```MAKEFLAGS=-j32```
> Build deps, app, rel targets really in that order

- erlang.mk
- plugins/elvis.mk
Given that 'make all' is the default build, it seems surprising to
delete this without an explicit request for a 'distclean'.
@jfacorro could perhaps shed some light on why this behaviour
was initially included.
> Prevent 'make all' from removing elvis

- packages.v1.tsv
- packages.v1.txt
- packages.v2.tsv
The following package is renamed and the packages.* files are duly updated. The renamed package: https://github.com/jj1bdx/exsplus128/
> Packages: rename exsplus to exsplus128

- README.md
I just spotted this `pkg-search n=STRING` typo in the README. 
Sorry about the spaces. I can restore them if you want.
> Fix pkg-search typo

- core/deps.mk
- erlang.mk
Print helpful error message in case a dependency doesn't have a Makefile to build it.
> Require makefile to build dep. Fixes #218.

- erlang.mk
- plugins/bootstrap.mk
Hi,
I made unescaped version of templates, to simplify adding new templates without boilerplate escaping.
new version: 
```makefile
define bs_appsrc
{application, $(PROJECT), [
{description, ""},
{vsn, "0.1.0"},
{modules, []},
{registered, []},
{applications, [
kernel,
stdlib
]},
{mod, {$(PROJECT)_app, []}},
{env, []}
]}.
endef
```
old version:
```makefile
bs_appsrc = "{application, $(PROJECT), [" \
"	{description, \"\"}," \
"	{vsn, \"0.1.0\"}," \
"	{modules, []}," \
"	{registered, []}," \
"	{applications, [" \
"		kernel," \
"		stdlib" \
"	]}," \
"	{mod, {$(PROJECT)_app, []}}," \
"	{env, []}" \
"]}."
```
I modified also **new** target to handle TEMPLATE and NAME directly (without named params):
```bash
$ make new gen_server my_gen_srv
``` 
vs old:
```bash
$ make new t=gen_server …
```
> handling unescaped templates and new 'new' target

- plugins/c_src.mk
* This patch ensures building the NIF code under`c_src`
even on running `make tests`
* When `c_src/Makefile` exists:
* Split the Makefile invocation dependency into `app-c_src`
* Invoke `app-c_src` also in `test-build` as well as `app`
* When `c_src/Makefile` does not exist:
* Add `$(C_SRC_ENV) $(C_SRC_OUTPUT)` dependencies to `test-build`
> Build NIF C code also on tests

- test/Makefile
* FreeBSD shell does not accept `&>` as the redirect operator;
Explicitly rewrite `&>/dev/null` to `>/dev/null 2>&1`
as a workaround
* This will not break other shells (confirmed on OS X 10.10.3)
> Fix test/Makefile for FreeBSD shell redirection compatibility

- Makefile
- erlang.mk
For me, I like to know which version I have, when running `make help` for instance.
> Update version when building erlang.mk.

- packages.v1.tsv
- packages.v1.txt
- packages.v2.tsv
This returns a find... error on OSX IIRC we've seen this before & I assume its unrelated to edown itself.
```
dch 🍺  /r/e/erlang.mk git:edown ❯❯❯make check p=edown
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C test pkg-edown
Setting up app.
cat packages.v2.tsv | awk 'BEGIN { FS = "\t" }; { print $1 "\t" $3 "\t" $5 "\t" $6 }' > packages.v1.tsv
cp packages.v1.tsv packages.v1.txt
awk 'FNR==1 && NR!=1{print ""}1' core/core.mk core/deps.mk plugins/protobuffs.mk core/erlc.mk core/docs.mk core/test.mk plugins/asciidoc.mk plugins/bootstrap.mk plugins/c_src.mk plugins/ci.mk plugins/ct.mk plugins/dialyzer.mk plugins/edoc.mk plugins/elvis.mk plugins/erlydtl.mk plugins/escript.mk plugins/eunit.mk plugins/relx.mk plugins/shell.mk plugins/triq.mk plugins/xref.mk plugins/cover.mk \
| sed …
```
> Add package edown to the index

- core/deps.mk
Consider the following test:
```sh
elif [ 0 != `find ... | xargs grep -ci rebar` ]; then
```
find(1) may return no file at all and xargs has nothing on its stdin. In this case, GNU xargs (from findutils) still executes the given command and grep(1) returns `0`.
However, FreeBSD's xargs for instance does not run the command at all if there is nothing on stdin. Therefore nothing is printed on stdout and the test becomes:
```sh
elif [ 0 != ]; then
```
This triggers a warning from the shell:
```
[: !=: argument expected
```
Prepending both operands with a literal `x` fixes the problem.
For consistency's sake, I modified the two other tests as well, though I didn't have any problem with them.
> dep_autopatch: Ensure ['s `!=` operator has operands

- core/deps.mk
... before writing to it.
This fixes the following error which is logged with a fresh checkout:
```
/bin/sh: cannot create (...)/.erlang.mk/deps.log: No such file or directory
```
> core/deps.mk: Ensure `$(ERLANG_MK_TMP)` is created

- core/deps.mk
As result of this conversation on same issue:
https://github.com/ninenines/erlang.mk/pull/297
> Replace 'xargs' with 'find -exec' for portability reasons

- core/core.mk
Currently build.config can be placed in a different directory via
something like:
ERLANG_MK_BUILD_CONFIG = tools/build.config
but if the name is changed:
ERLANG_MK_BUILD_CONFIG = .erlang-mk.config
it will be ignored.
> Fix build config renaming

- core/erlc.mk
- core/test.mk
This ensures all generated dependencies are prepared and the `.d` file is ready before the actual build is started.
> Generate `$(PROJECT).d` before calling `make app-build`

- test/Makefile
This required two changes:
1. Modifying a file inplace using `-i` is not portable. GNU sed does not require an argument; the absence of it meaning it should change the file inplace. sed found on FreeBSD and probably other BSDs' require an argument, so inplace modification should be specified as:
```
sed -i ''
```
Obviously, both -i are incompatible... The "solution" is to not do inplace modification.
2. The `[1addr]i` command takes its argument on the next line according to the standard (though, it's not explicitely stated, the syntax example suggests that). GNU sed accepts to have its argument on the same line as the command, but not FreeBSD's sed.
> test/Makefile: Support non-GNU sed

- core/core.mk
- test/Makefile
The goal is to be able to run `make erlang-mk` and fetch `erlang.mk` from a fork on GitHub for instance, while waiting for patches to be reviewed.
> core.mk: Allow to take erlang.mk from an alternate Git repository

- plugins/c_src.mk
`find`, the underlying command of `core_find`, [does not support multiple patterns
after -name](http://stackoverflow.com/questions/1133698/find-name-pattern-that-matches-multiple-patterns).  This patch fixes multi-pattern use in `c_src.mk` by calling `core_find`
once for each pattern.
> fix multiple patterns used on core_find

- Makefile
Option `--rfc-3339` is specific to GNU Coreutils' date(1). This change fixes the use of `make summary` on other platforms such as FreeBSD.
> Use '+%F %T%z' to format the timestamp

- test/Makefile
- test/core_app.mk
- test/core_deps.mk
- test/core_plugins.mk
- test/core_upgrade.mk
The previous code did:
```sh
if `<code that prints nothing on stdout>`; then ...
```
So the test failed but not for the good reason. The forked shell printed:
```
/bin/sh: gmake[2]:: not found
```
Now, both `"Run 'make ...'"` tests are simplified and do not rely on backticks and test(1) anymore. Either the output is inspected or the exit code is checked.
> Do not try to execute an empty shell script in core-plugins-one test

- core/deps.mk
The generated Makefile said:
```
PROJECT = core_app_pt_erlc_opts
BUILD_DEPS = my_pt_dep
...
```
However, in `core/deps.mk`, the variable `$(ALL_DEPS_DIRS)` calls `$(dep_name)` to get the name of the dependency, and `$(dep_name)` checks the value of either `$(dep_something)` or
`$(pkg_something_name)`. In this test case, none was set, leading to `$(ALL_DEPS_DIRS)` being empty and no dependency was built.
Adding `dep_my_pt_dep = null` to the generated Makefile is enough, though the fetch method is obviously incorrect. The generated Makefile now looks like:
```make
PROJECT = core_app_pt_erlc_opts
BUILD_DEPS = my_pt_dep
dep_my_pt_dep = null
...
```
> Fix core-app-pt-erlc-opts so the dependency is built

- core/core.mk
- core/deps.mk
- core/erlc.mk
The `-n` flag is not standard and not portable. It is supported by many Bourne shell to suppress the trailing newline character. But some old shells do not support this and "-n" is printed.
This is the case for instance on some old versions of Mac OS X where `/bin/sh` is Bash 3.2.
> Use `:` as a noop instead of `echo -n`

- core/core.mk
- test/core_upgrade.mk
If the local build.config has changes compared to upstream's master branch, and `$(ERLANG_MK_COMMIT)` also brings changes to this file, copying the local file to the checkout before switching to `$(ERLANG_MK_COMMIT)` caused git-checkout(1) to abort with:
```
error: Your local changes to the following files would be overwritten by checkout:
build.config
Please, commit your changes or stash them before you can switch branches.
Aborting
```
> make erlang-mk: Copy build.config after switching to $(ERLANG_MK_COMMIT)

- plugins/bootstrap.mk
- plugins/c_src.mk
Use `$(file)` macro to write the generated files. This avoids environment pollution with a large amount of Erlang code.
> Do not export templates as environment variables

- core/core.mk
- core/deps.mk
- core/erlc.mk
- test/Makefile
This helps to debug some recipes which are more than one line of shell script, for instance when the recipe is a shell `for` loop.
> V=2 causes `set -x` to be set on forked shells

- core/deps.mk
- test/core_deps.mk
... not the first.
`dep_autopatch` can be an expensive macro, in particular because it executes Erlang. So if `NO_AUTOPATCH` is set, it's best to avoid calling `dep_autopatch` as the result will be unused anyway.
> deps.mk: In dep_target, call dep_autopatch during the second eval

- core/deps.mk
My bad, I had closed the following pull request by putting this patch in a separate branch:
https://github.com/ninenines/erlang.mk/pull/388
> autopatch: do not run autoreconf if configure script already exists

- doc/src/guide/app.asciidoc
> Fix invalid link to documentation

- index/bitcask.mk
Basho uses the develop branch (not master) and that one is most up-to-date
> Use the develop branch

- core/erlc.mk
Extended Mode uses { and } as special characters. Making grep
implementations other then GNU grep fail (see
http://www.gnu.org/software/grep/manual/grep.html#Basic-vs-Extended).
---
I assume -E is a typo for -e as Extended Mode is not needed for that grep.
Resolves #523.
> Do not use grep Extended Mode

- plugins/ct.mk
- test/plugin_ct.mk
* Include $(APPS_DIR)/*/ebin in CT_RUN
* test-build before ct-apps
* Test that my_lib is accessible from my-app ct
Currently ct is not really working for multi-application repositories. This PR addresses and fixes the issue though further restructuring of the CT plugin might be advisable in the future.
Local test run failed on dialyzer tests that I think are unrelated.
> Fix ct for multi-app repositories

- plugins/bootstrap.mk
- test/plugin_bootstrap.mk
Every .erl source file will need at least a -module and a single -export
definition. With the empty template a file can be quickly created that
already populates -module with the right value as well as an empty
export field that can quickly be filled.
> Add empty 'module' template

- core/compat.mk
- test/core_compat.mk
When preparing erlc_opts, remove all comma/whitespace pairs instead of
just the first
> Remove spaces after commas globally

- core/erlc.mk
When the last git tag contains '/' character, compilation of .app file fails because it interfers with sed regexp syntax
> Fix .app compilation when a git tag contains a '/'

- plugins/cover.mk
Fix possible division by zero in case if a module doesn't export any functions. See #409 for more details.
> Fix possible 'badarith' error for cover

- core/deps.mk
- test/core_deps.mk
This is a fix for #447 and possibly a partial fix for #380.
In summary, apps in `APPS_DIR` cannot reliably `include_lib` each other's headers.  This PR fixes that.
> Allow APPS_DIR apps to include_lib each other's headers

- doc/src/guide/external_plugins_list.asciidoc
- index/find_crate.mk
- index/rust.mk
This is a plugin and helper library to build Rust ports/NIFs/drivers inside Erlang apps.  The [rust.mk readme](https://github.com/goertzenator/rust.mk) explains what it all does.
> Add Rust plugin and helper library to index

- index/rust.mk
- index/rust_mk.mk
I've misunderstood a few things about plugins and have recast the Rust.mk plugin in the image of `reload_mk.mk`.
> Fix rust.mk package info

- core/core.mk
- core/erlc.mk
- doc/src/guide/app.asciidoc
- test/core_app.mk
I have many projects in which the application callback module (mod key in .app) is not called $(PROJECT)_app.erl, this is a very small change to make it configurable.
> Add PROJECT_MOD var to make the app callback module configurable

- index/chumak.mk
- index/erlangzmq.mk
This is the same package as `erlangzmq` only name and license are changed.
If possible, please delete `erlangzmq` from the index.
> Add package chumak to the index

- plugins/dialyzer.mk
- test/plugin_dialyzer.mk
Splitting arguments on `-` was dangerous: if a path contained such a character, it would be split and the second half thrown away by the filtering.
Now, `$(ERLC_OPTS)` is passed to erl(1) after `-extra`. Thus arguments parsing is done by the shell and we only have to call `init:get_plain_arguments/0` to get them as a list.
> dialyzer.mk: Use the shell to parse command line args

- index/exec.mk
erlexec now requires that particular name in order to successfully boot.
> Fix erlexec application name

- core/deps-tools.mk
To do that, we simply include the PID of the Make process in temporary file.
We also compare the finished temporary file with the actual target file. If they are different, the temporary file is moved to the final target, otherwise, we just get rid of the temporary file. This way, the target timestamp stays the same if the content does not change.
> Fix concurrent creation of `recursive-*deps-list.log` files

- test/core_query.mk
It was previously "pinned" to its `master` branch. Unforunately, the testcase started to fail after `farwest` changed its own pinning of `cowlib`.
By pinning to a specific version (or commit in this case) of `farwest`, we make sure this won't happen again.
> test/core_query.mk: Pin `farwest` in `core-query-deps-no-duplicates`

- core/test.mk
- test/core_app.mk
In commit c55d0dcd6182983521d4ab34478cfe4b093edb12, the recipe was improved to only rebuild out-of-date test files (not everything as it was the case before).
However in the process, the exit status of the Erlang compiler was not checked anymore, leading to build failures in the test directory to be ignored. This patch fixes this bug.
> core/test.mk: Abort build if a test file fails to compile

- core/deps-tools.mk
To reproduce:
```
git clone https://github.com/rabbitmq/inet_tcp_proxy.git
cd inet_tcp_proxy
$ make BRANCH=master QUERY='name fetch_method repo version absolute_path' query-deps
/bin/sh: /home/lbakken/development/rabbitmq/umbrella/deps/inet_tcp_proxy/.erlang.mk/recursive-tmp-deps-231462.log: No such file or directory
rm: cannot remove '/home/lbakken/development/rabbitmq/umbrella/deps/inet_tcp_proxy/.erlang.mk/recursive-tmp-deps-231462.log': No such file or directory
make: *** [erlang.mk:7642: /home/lbakken/development/rabbitmq/umbrella/deps/inet_tcp_proxy/.erlang.mk/recursive-deps-list.log] Error 1
```
> Fix `query-deps` for projects without deps

- core/compat.mk
- index/cowboy.mk
- test/core_compat.mk
- test/core_deps.mk
We now provide the version as a tagged tuple indicating whether this is a branch, tag or ref. This should help rebar automatically upgrade dependencies, and remove an annoying warning when rebar is used.
In order to detect the type of version the dependencies must be available, therefore the rebar.config target now depends on the deps target.
To test this the Cowboy package version had to be changed from 1.0.4 to master. This is a breaking change, but I do not expect too many people to still use 1.0.4.
#900
> Improve rebar.config generation

- core/deps.mk
https://github.com/ninenines/erlang.mk/issues/1014
> Fix infinite loop when fetching amqp_client deps via Hex

- .github/workflows/ci.yaml
- CHANGELOG.asciidoc
- build.config
- core/core.mk
- core/deps-tools.mk
- core/deps.mk
- core/elixir.mk
- core/erlc.mk
- doc/src/guide/book.asciidoc
- doc/src/guide/elixir.asciidoc
- index/elixir.mk
- plugins/escript.mk
- plugins/eunit.mk
- plugins/hex.mk
- test/core_elixir.mk
- test/plugin_eunit.mk
Heavily modified version of https://github.com/ninenines/erlang.mk/pull/979
> Native Elixir support
