- README.md
- core/deps.mk
- erlang.mk
One squashed commit, replacing PR 190.
Apologies for getting you involved while I'm still learning how to use more advanced features of git.
> add svn dependencies

- erlang.mk
- plugins/relx.mk
Updated relx to version v1.1.0 and tested with the setup from issue #193
> Updated relx to version v1.1.0

- erlang.mk
- plugins/edoc.mk
- test/Makefile
Implemented in the same way as TEST_DEPS. A test case that generates edoc using edown is included.
> Adds DOC_DEPS; fixes #75

- packages.v1.tsv
- packages.v1.txt
- packages.v2.tsv
https://github.com/erlanger/nodefinder
> Add package nodefinder to the index

- core/deps.mk
- erlang.mk
This will also address issue #217. At least for the given example repo.
I took a slightly different approach to that suggested in #217, by looking for the `rebar` script instead of always patching.
> always patch deps that are listed in the autopatch var.

- plugins/elvis.mk
> elvis updated to 0.2.5-beta2

- core/deps.mk
$$$$ after replace by make is $$ and in bash it is pid of process.
> Fix deps regexp

- core/core.mk
- test/Makefile
Removes $(ERLANG_MK_TMP) directory on make distclean.
resolves #356
> add distclean-tmp target to core

- core/erlc.mk
the new method of generating .app files strips newlines, resulting in very ugly files that still contain loads of whitespace.
> [READY] prettify generated .app files

- plugins/erlydtl.mk
- test/plugin_erlydtl.mk
> Ensure that modules generated from erlydtl are listed in .app file

- index/mimerl.mk
this patch add mimerl to the index
> add mimerl to the index

- index/slack.mk
> Add package slack to the index

- index/jsone.mk
**jsone**
An Erlang library for encoding, decoding JSON data.
https://github.com/sile/jsone
> Add package jsone to the index

- index/jesse.mk
Old repository is no longer actively maintained
https://github.com/klarna/jesse/blob/master/README.md
> Old repository is no longer actively maintained

- plugins/bootstrap.mk
> Correct output of bootstrap help target

- index/geode.mk
Adding geode - "Geohash / proximity searches in pure, uncut Erlang"
> add geode project

- index/zabbix_sender.mk
Simple native Zabbix sender for Erlang applications
> Add package zabbix_sender to the index

- index/erlangzmq.mk
Resubmitting PR for erlangzmq with dialyzer warnings fixed.
> Add package erlangzmq to the index

- core/core.mk
- core/deps-tools.mk
- core/deps.mk
- doc/src/guide/deps.asciidoc
- test/core_query.mk
> Add the query-deps family of targets

- index/jsx.mk
We need this lite change to use jsx with erlang.mk again.
> Update jsx master -> main branch repository

- index/cuttlefish.mk
https://github.com/Kyorai/cuttlefish
> Update canonical cuttlefish package location

- test/core_deps.mk
> test/core_deps.mk: Fix jquery branch name

- plugins/dialyzer.mk
Dialyzer no longer supports -Wrace_conditions as of Erlang 25
Closes #941.
> Drop -Wrace_conditions from Dialyzer options
